name: Flutter Setup
description: A Flutter environment for use with GitHub Actions
author: Lumis Labs <https://github.com/lumis-labs>

inputs:
  os:
    description: The operating system to use (e.g. windows, ubuntu, macos)
    required: true
  architecture:
    description: The architecture to use (e.g. x64, arm64)
    required: true
  channel:
    description: The flutter channel to use (e.g. stable, beta, dev)
    required: true
  version:
    description: The flutter version to use (e.g. 3.24.1 or latest)
    required: true

runs:
  using: node20
  main: dist/index.js
