name: Flutter Setup
description: A Flutter environment for use with GitHub Actions
author: "Lumis Labs <https://github.com/lumis-labs>"

branding:
  color: blue
  icon: feather

inputs:
  channel:
    description: "The Flutter channel to use (e.g. stable, beta, dev)"
    required: false
  version:
    description: "The Flutter version to use (e.g. 3.24.1)"
    required: false
  os:
    description: "The operating system to use (e.g. windows, linux, macos)"
    required: false
    default: linux
  architecture:
    description: "The architecture to use (e.g. arm64, x64)"
    required: false
    default: x64

runs:
  using: composite
  steps:
    - name: Download flutter URI tool
      run: |
        URI="https://github.com/lumis-labs/flutter-setup/releases/download/v1.0.0/flutter-setup-$OS-$ARCHITECTURE"
        curl -fL $URI -o ${{ github.action_path }}/flutter_setup
        chmod +x ${{ github.action_path }}/flutter_setup
      shell: bash
      env:
        OS: ${{ inputs.os }}
        ARCHITECTURE: ${{ inputs.architecture }}

    - name: Run flutter URI tool
      run: |
        FLUTTER_URI=$(${{ github.action_path }}/flutter_setup \
           ${{ inputs.os }} \
           ${{ inputs.architecture }} \
           ${{ inputs.channel }} \
           ${{ inputs.version }})
        echo "FLUTTER_URI=$FLUTTER_URI" >> $GITHUB_ENV
      shell: bash

    - name: Download Flutter SDK
      run: |
        curl -fL $FLUTTER_URI -o flutter.tar.xz
        tar -xJf flutter.tar.xz
      shell: bash

    - name: Set up Flutter environment
      run: |
        echo "FLUTTER_ROOT=flutter" >> $GITHUB_ENV
        echo "PATH=flutter/bin:$PATH" >> $GITHUB_ENV
      shell: bash
