name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        architecture:
          - x64
        include:
          - os: macos-latest
            architecture: arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          os: ${{ matrix.os }}
          architecture: ${{ matrix.architecture }}
          cache: true
      - run: flutter --version
      - run: dart --version
