name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        architecture:
          - x64

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          os: ${{ matrix.os }}
          architecture: ${{ matrix.architecture }}
          channel: stable
          version: 3.24.1
          cache: true
      - run: flutter --version
      - run: dart --version
