name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        architecture:
          - x64
        include:
          - os: macos-latest
            architecture: arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Run
        uses: ./
        with:
          os: ${{ matrix.os }}
          architecture: ${{ matrix.architecture }}

      - name: Test
        run: flutter --version
